# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

grad <- function(Model, par, h = 1e-6) {
    .Call(`_optimg_grad`, Model, par, h)
}

gradN <- function(f, par, h = 1e-6, order = 1L) {
    .Call(`_optimg_gradN`, f, par, h, order)
}

SGD <- function(fn, startvalue, gr, h = 1e-6, maxit = 10L, tol = 1e-8, verbose = FALSE) {
    .Call(`_optimg_SGD`, fn, startvalue, gr, h, maxit, tol, verbose)
}

STGD <- function(fn, startvalue, gr, h = 1e-6, maxit = 10L, tol = 1e-8, verbose = FALSE) {
    .Call(`_optimg_STGD`, fn, startvalue, gr, h, maxit, tol, verbose)
}

LMM <- function(fn, startvalue, gr, h = 1e-6, maxit = 10L, tol = 1e-8, verbose = FALSE) {
    .Call(`_optimg_LMM`, fn, startvalue, gr, h, maxit, tol, verbose)
}

